### ISSUE TITLE
FEATURE REQUEST: learning rate decay

### ISSUE THREAD

**Issue by brantbzhang** [reinforceio/tensorforce#230] opened 2017-11-14 01:35 UTC

**Comment by Mazecreator** [comment] 2017-11-14 01:46
I was going to ask if this feature existed.  If not, it would be good to add.

**Comment by michaelschaarschmidt** [comment] 2017-11-18 18:23
Actually a duplicate of https://github.com/reinforceio/tensorforce/issues/103 so let us keep discussion there if someone wants to get started

**Closed by michaelschaarschmidt** 2017-11-18 18:23 UTC
