### ISSUE TITLE
Dropped timesteps in replay memory lead to empty updates and crashes

### ISSUE THREAD

**Issue by krfricke** [reinforceio/tensorforce#353] opened 2018-02-26 09:40 UTC
In Replay.tf_retrieve_timesteps, lines 55 and 56, terminal timesteps are excluded from a sampled batch:

https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/memories/replay.py#L56 

This can lead to empty update batches, especially in cases such as CartPole with short episode lengths. For instance, running DDPG with batch_size = 4 often leads to crashes because of empty batches (Thanks @devnag_twitter for pointing that out).

As discussed, the solution could be to exclude terminal timesteps from selection to begin with, and/or employ a loop to fill empty spaces.

**Comment by yellowbee686** [comment] 2018-03-02 12:56
I've played with DQN and it may has the same problem, 
First the problem is in PrioritizedReplay, where 
priority_indices = tf.squeeze(tf.where(condition=mask))
may cause priority_indices to be a tensor with no shape
so I change the code to priority_indices = tf.squeeze(tf.where(condition=mask), [1])

then the second problem comes:
InvalidArgumentError : Inputs to operation dqn/observe-timestep/cond/optimization/clipped-step/step/adam/step/loss/loss-per-instance/Select of type Select must have the same size and shape.  Input 0: [100] != input 1: [0]

the error code is in 
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/q_model.py#L149

which I've debug it because the next_q_value is a tensor with shape [] and it because in q_model.tf_loss_per_instance, the action_taken is a tensor with shape [].

**Comment by michaelschaarschmidt** [comment] 2018-03-02 13:02
Just quickly interjecting that prioritised replay is still under construction and not meant to be used yet because the priority update is tricky in pure tensorflow (and not implemented yet)

**Comment by yellowbee686** [comment] 2018-03-02 17:06
@michaelschaarschmidt  thanks for replying, then I change the memory mode to replay, the second problem still occurs.

**Comment by michaelschaarschmidt** [comment] 2018-03-03 10:18
Should be fixed via https://github.com/reinforceio/tensorforce/commit/1109dc5df81e2ddeffd83b9843d50710a014d433, introduced a simple resampling loop, dqn test and quickstart working for me, hope this solves it.

**Comment by yellowbee686** [comment] 2018-03-03 10:37
Thanks, I'll test it on Monday!

**Comment by yellowbee686** [comment] 2018-03-05 02:01
@michaelschaarschmidt  the replay problem is solved, thanks!

**Comment by michaelschaarschmidt** [comment] 2018-03-05 08:38
great

**Closed by michaelschaarschmidt** 2018-03-05 08:38 UTC
