### ISSUE TITLE
TRPO struggling with CartPole-v0 from quick start

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [reinforceio/tensorforce#50] opened 2017-07-24 22:12 UTC
After [running](https://gist.github.com/AdamStelmaszczyk/8451948a806837af5b1fe930a4285d76#file-gistfile1-txt) `python examples/quickstart.py` (3000 episodes), the average reward from last 100 episodes is only 33.38. I would expect it to be close to the maximum, 200. Especially that it reached it couple of times before, e.g. on episode 1469, however later it deteriorates.

I also tried running it with provided command:
```
python examples/openai_gym.py CartPole-v0 -a TRPOAgent -c examples/configs/trpo_cartpole.json -n examples/configs/trpo_cartpole_network.json
```
However the [results](https://gist.github.com/AdamStelmaszczyk/8451948a806837af5b1fe930a4285d76#file-gistfile2-txt) were also unsatisfactory:

```
[2017-07-24 23:58:58,363] Finished episode 4050 after 61 timesteps
[2017-07-24 23:58:58,363] Episode reward: 61.0
[2017-07-24 23:58:58,363] Average of last 500 rewards: 63.346
[2017-07-24 23:58:58,364] Average of last 100 rewards: 62.33
```

**Comment by michaelschaarschmidt** [comment] 2017-07-24 22:17
Which python version?
I just kicked off a run and am seeing a steady increase:

[2017-07-24 23:15:25,367] Finished episode 300 after 136 timesteps
[2017-07-24 23:15:25,367] Episode reward: 136.0
[2017-07-24 23:15:25,368] Average of last 500 rewards: 48.662
[2017-07-24 23:15:25,368] Average of last 100 rewards: 138.07

**Comment by AdamStelmaszczyk** [comment] 2017-07-24 22:18
Python 2.7.12.

**Comment by michaelschaarschmidt** [comment] 2017-07-24 22:21
Ok, I can have a go at reproducing that tomorrow. There might however always be problematic runs with bad seeds, but seems fine in 3.6.2

**Comment by AdamStelmaszczyk** [comment] 2017-07-24 22:25
>  but seems fine in 3.6.2

Could you please post a log from a run on 3000 episodes with Python 3.6.2?

**Comment by michaelschaarschmidt** [comment] 2017-07-24 22:31
Have to leave for today but here is first 1500 from the previous run before i killed it..I can look at this tomorrow. In general, I believe you that performance might go down again, because we did not implement KL-divergence annealing where we stop updating after a while, but cartpole is considered solved if there is 100 eps with 200 reward I think:

17-07-24 23:23:54,495] Finished episode 1150 after 200 timesteps
[2017-07-24 23:23:54,495] Episode reward: 200.0
[2017-07-24 23:23:54,495] Average of last 500 rewards: 91.75
[2017-07-24 23:23:54,495] Average of last 100 rewards: 174.28
[2017-07-24 23:24:11,088] Finished episode 1200 after 200 timesteps
[2017-07-24 23:24:11,088] Episode reward: 200.0
[2017-07-24 23:24:11,088] Average of last 500 rewards: 105.69
[2017-07-24 23:24:11,088] Average of last 100 rewards: 197.2
[2017-07-24 23:24:27,112] Finished episode 1250 after 200 timesteps
[2017-07-24 23:24:27,113] Episode reward: 200.0
[2017-07-24 23:24:27,113] Average of last 500 rewards: 118.014
[2017-07-24 23:24:27,113] Average of last 100 rewards: 190.1
[2017-07-24 23:24:43,777] Finished episode 1300 after 80 timesteps
[2017-07-24 23:24:43,777] Episode reward: 80.0
[2017-07-24 23:24:43,777] Average of last 500 rewards: 130.174
[2017-07-24 23:24:43,777] Average of last 100 rewards: 183.11
[2017-07-24 23:25:03,404] Finished episode 1350 after 200 timesteps
[2017-07-24 23:25:03,404] Episode reward: 200.0
[2017-07-24 23:25:03,404] Average of last 500 rewards: 143.536
[2017-07-24 23:25:03,404] Average of last 100 rewards: 190.07
[2017-07-24 23:25:22,964] Finished episode 1400 after 200 timesteps
[2017-07-24 23:25:22,964] Episode reward: 200.0
[2017-07-24 23:25:22,964] Average of last 500 rewards: 157.062
[2017-07-24 23:25:22,964] Average of last 100 rewards: 198.56
[2017-07-24 23:25:41,130] Finished episode 1450 after 200 timesteps
[2017-07-24 23:25:41,130] Episode reward: 200.0
[2017-07-24 23:25:41,130] Average of last 500 rewards: 170.024
[2017-07-24 23:25:41,130] Average of last 100 rewards: 200.0
[2017-07-24 23:25:59,222] Finished episode 1500 after 200 timesteps
[2017-07-24 23:25:59,223] Episode reward: 200.0
[2017-07-24 23:25:59,223] Average of last 500 rewards: 181.628
[2017-07-24 23:25:59,223] Average of last 100 rewards: 200.0
[2017-07-24 23:26:16,896] Finished episode 1550 after 200 timesteps
[2017-07-24 23:26:16,896] Episode reward: 200.0
[2017-07-24 23:26:16,896] Average of last 500 rewards: 190.89
[2017-07-24 23:26:16,896] Average of last 100 rewards: 200.0
[2017-07-24 23:26:35,774] Finished episode 1600 after 200 timesteps
[2017-07-24 23:26:35,774] Episode reward: 200.0
[2017-07-24 23:26:35,775] Average of last 500 rewards: 195.774
[2017-07-24 23:26:35,775] Average of last 100 rewards: 200.0

**Comment by AdamStelmaszczyk** [comment] 2017-07-24 22:43
> cartpole is considered solved if there is 100 eps with 200 reward I think

Ah, I forgot about that, cheers. Checked on https://gym.openai.com/envs/CartPole-v0 and it's even lighter:

> CartPole-v0 defines "solving" as getting average reward of 195.0 over 100 consecutive trials.

However it still looks like my [run](https://gist.github.com/AdamStelmaszczyk/8451948a806837af5b1fe930a4285d76#file-gistfile1-txt) of `python examples/quickstart.py` will not pass, but the second one, the one with longer command - would.

When time allows please try running `python3 examples/quickstart.py` till the end (it's problematic for me to setup now TF and all the other dependencies for Python 3).

**Comment by AdamStelmaszczyk** [comment] 2017-07-24 23:55
I [run](https://gist.github.com/AdamStelmaszczyk/ffef406de16c84824b9ef609d25d469d) it second time and now it looks much better.

> There might however always be problematic runs with bad seeds

I think it might be this, by bad seeds you mean the network weights were drawn "unluckily" (i.e. in such a way, that later TRPO could not get 200 for 100 episodes)? Would it mean it was getting stuck in local extremums (while finding weights) that were far from the optimum? That would be sad, as the network is small (2 layers with 32 neurons). If that's the case then one have to run TRPO multiple times and record "the best run" (I'm thinking about more complex env)? Or there are parameter changes that should help?

**Comment by michaelschaarschmidt** [comment] 2017-07-25 06:47
Hi, ok good. So 2 issues:
- Yes, there can be local extremums always and the algorithm cannot escape. This is why it makes sense to add a heuristic for the learning rate that increases it when there is no improvement or decreases it when it gets worse. This is always the case with reinforcement learning
- Another thing is that this is a stochastic policy, so it samples an action. This means it will always do slightly random things even at 200. Hence, another thing one can do is to move from sampling to deterministic acting (there is a flag in the act method for this).

Hope this helps and I would close the issue then - this is just the general nature of RL algorithms, not a bug.

**Closed** 2017-07-25 07:24 UTC

**Comment by AdamStelmaszczyk** [comment] 2017-07-25 11:39
Thank you Michael, that helps a lot. Keep up the good work.
