### ISSUE TITLE
[BUG] The node 'ppo/..dropout..` has inputs from different frames. (memory branch)

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#317] opened 2018-01-27 15:50 UTC
Looks like Dropout has issues on the new branch. Removing `dropout` from my layer-specs fixes the issue. Error:

```shell
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/step_1/while/step/gradients/ppo/observe-timestep/cond/step_1/while/step/loss/predict/apply/apply_5/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/step_1/while/step/loss/predict/apply/apply_5/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/step_1/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_1' is in frame ''.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 106, in <module>
    main()
  File "run.py", line 99, in main
    env.train_and_test(agent, early_stop=args.early_stop, n_tests=args.runs)
  File "/home/ubuntu/btcbot/btc_env.py", line 447, in train_and_test
    runner.run(timesteps=n_train, max_episode_timesteps=n_train)
  File "/home/ubuntu/tensorforce/tensorforce/execution/runner.py", line 127, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/ubuntu/tensorforce/tensorforce/agents/agent.py", line 217, in observe
    reward=self.observe_reward
  File "/home/ubuntu/tensorforce/tensorforce/models/model.py", line 1129, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/step_1/while/step/gradients/ppo/observe-timestep/cond/step_1/while/step/loss/predict/apply/apply_5/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/step_1/while/step/loss/predict/apply/apply_5/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/step_1/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_1' is in frame ''.
```

**Comment by michaelschaarschmidt** [comment] 2018-02-09 15:57
Thanks for notifying us, this will probably be a bit on the lower end of todo before merging because dropout is not a critical feature, but we will try to look into it at some point

**Comment by AlexKuhnle** [comment] 2018-02-10 13:04
Does this actually still happen, on the new branch and everything? Just to check...

**Comment by lefnire** [comment] 2018-02-10 15:20
Yes, tested as of 8236d94

**Comment by AlexKuhnle** [comment] 2018-02-10 16:03
I can't reproduce the problem with the following command line (after adding a dropout layer to the network json):
```bash
python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json -e 2000 -m 200
```

**Comment by lefnire** [comment] 2018-02-10 16:12
Will try on an example config, and post my own config when I get a chance. All my stuff follows [tforce_btc_trader](https://github.com/lefnire/tforce_btc_trader); but that's hard to digest, so I'll try to create isolated situations.

**Comment by lefnire** [comment] 2018-03-03 18:02
I think it's for networks with internals (LSTMs). Try updating `mlp2_lstm_network` as:

```json
[
  {"type": "dense", "size": 32},
  {"type": "dense", "size": 32},
  {"type": "dropout", "rate": 0.5},
  {"type": "internal_lstm", "size": 32}
]
```

and run `python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_lstm_network.json -e 2000 -m 200`. Latest test as of 654ed61df8f0560014a429c520c0d3df1114dac9.

```shell
CUDA_VISIBLE_DEVICES= python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_lstm_network.json -e 2000 -m 200
/home/lefnire/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:gym.envs.registration:Making new env: CartPole-v0
WARNING:tensorflow:From /home/lefnire/tensorforce/tensorforce/core/distributions/categorical.py:66: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From /home/lefnire/tensorforce/tensorforce/core/distributions/categorical.py:66: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Graph was finalized.
2018-03-03 09:58:27.211688: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-03 09:58:27.214136: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-03-03 09:58:27.214170: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: lefnire-ubuntu
2018-03-03 09:58:27.214178: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: lefnire-ubuntu
2018-03-03 09:58:27.214205: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.111.0
2018-03-03 09:58:27.214230: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.111.0
2018-03-03 09:58:27.214238: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.111.0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:examples/openai_gym.py:Starting PPOAgent for Environment 'OpenAIGym(CartPole-v0)'
Traceback (most recent call last):
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_2/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_2/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/openai_gym.py", line 140, in <module>
    main()
  File "examples/openai_gym.py", line 132, in main
    episode_finished=episode_finished
  File "/home/lefnire/tensorforce/tensorforce/execution/runner.py", line 112, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/lefnire/tensorforce/tensorforce/agents/agent.py", line 226, in observe
    reward=self.observe_reward
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 1243, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_2/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_2/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.
```

**Comment by trickmeyer** [comment] 2018-04-04 20:57
I'm having an issue with my PPO baseline network that seems similar.  Here's how I had it configured:

```
        baseline_mode='network',
        baseline=dict(
            type='mlp',
            sizes=[32, 32]
        ),
        baseline_optimizer=dict(
            type='adam',
            learning_rate=0.001
        ),
```

And here's the error I get:

```
INFO:tensorflow:Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add/Identity' as input to 'ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_3' because they are in different while loops.
ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/Add/Identity while context: ppo/observe-timestep/cond/optimization/reward-estimation/discounted-cumulative-reward/scan_1/while/while_context
ppo/observe-timestep/cond/optimization/multi-step/step/while/Identity_3 while context: ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context
```

**Comment by RDTm** [comment] 2018-04-19 11:48
Similarly to Issue #376 , I also see that with the newest version of tensorforce pulled from the repository PPO does not work with Dropout layers.
I cloned a clean copy of the repo, the only change I made to the repository was adding a Dropout layer between the two Dense layers in examples/configs/mlp2_network.json.

`[
    {
        "type": "dense",
        "size": 32,
        "activation": "relu"
    },
    {
        "type": "dropout",
        "rate": 0.5
    },
    {
        "type": "dense",
        "size": 32,
        "activation": "relu"
    }
]`

I then ran the simplest of examples:
`python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json -e 2000 -m 200`

Which crashed giving this same:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_1/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/regularization-losses/apply/apply_1/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.`

So it is not only an issue with recurrent networks, at least not any more. It is very basic stuff that does not work. Is there any hope of fixing it any time soon? Or at least a better idea what part of PPO has problem with Dropout?

**Comment by Giezzy** [comment] 2018-04-19 13:08
> I then ran the simplest of examples:
> python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json -e 2000 -m 200

I just ran the example on Tensorforce 0.4.1 without problems. Which version are you using?

**Comment by RDTm** [comment] 2018-04-19 13:12
Python 3.5.2 ; Tensorflow 1.7.0
`
> import tensorforce
> tensorforce.__version__
'0.4.0'`

**Comment by AlexKuhnle** [comment] 2018-07-31 17:01
Is this still a problem in the most recent GitHub version?

**Comment by lefnire** [comment] 2018-07-31 18:55
Just tried with master & TF 1.9. CNN this time (not RNN):

```shell
File "/home/lefnire/tforce_btc_trader/btc_env.py", line 257, in train_and_test
    runner.run(timesteps=train_steps)
  File "/home/lefnire/tforce_btc_trader/tmp/tensorforce/tensorforce/execution/runner.py", line 113, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/lefnire/tforce_btc_trader/tmp/tensorforce/tensorforce/agents/agent.py", line 185, in observe
    reward=self.observe_reward
  File "/home/lefnire/tforce_btc_trader/tmp/tensorforce/tensorforce/models/model.py", line 1421, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 577, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1144, in run
    raise six.reraise(*original_exc_info)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1129, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1201, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 981, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_7/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_7/cond/Identity/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.
```

**Comment by AlexKuhnle** [comment] 2018-07-31 18:58
Alright, will check it out soon.

**Comment by AlexKuhnle** [comment] 2018-08-03 22:23
@all, should be fixed with the latest commit.

**Closed by AlexKuhnle** 2018-08-03 22:23 UTC
