### ISSUE TITLE
Gym Discrete() observation_space rank error

### ISSUE THREAD

**Issue by ImpulseAdventure** [reinforceio/tensorforce#169] opened 2017-10-14 06:39 UTC
Is there a way to run envs from OpenAI Gym that incorporate a `Discrete()` `observation_space`?

When launching gym environments with a Discrete(n) observation_space I encounter the error:
`tensorforce.exception.TensorForceError: Invalid input rank for linear layer: 1, must be 2.`

Example execution:
`python examples/openai_gym.py GuessingGame-v0 -a TRPOAgent -c examples/configs/trpo_agent.json -n examples/configs/trpo_network.json`

The same error is observed with a number of other gym envs in the toy_text and algorithmic categories.

If I manually revise the env to use a `spaces.Box()` observation_space, I can get them to work, but it would be nice if there was a way to use the environment as-is. My apologies if I have overlooked something simple in the tensorforce setup.

Congrats on building a fantastic RL framework!

**Comment by michaelschaarschmidt** [comment] 2017-10-14 07:26
Hey,

we will look into this - the gym action/state spaces are not always consistent unfortunately. We are in the midst of a large release (branch/merge on github in the next 3 days) so bear with us for a bit.

**Comment by ImpulseAdventure** [comment] 2017-10-20 06:51
Thanks very much Michael... looking forward to the upcoming release.

**Comment by AlexKuhnle** [comment] 2017-10-21 15:52
Hi @ImpulseAdventure,
I assume the problem is the following: We map the `Discrete` gym observation space to an integer state of shape `()` [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L72). However, all the layers we currently provide expect a tensor of float values, so to handle this correctly, you would need to implement an appropriate layer. A reasonable layer would, for instance, be an `Embedding` layer, which maps the index given by the `Discrete` space to the corresponding embedding, i.e. a float tensor which then could be passed through dense layers or so. Hope that makes sense.
PRs are always welcome, otherwise we can look into this at some point (might take a while, though).

**Comment by ImpulseAdventure** [comment] 2017-10-23 06:58
Great suggestion Alex... I had originally assumed that one could create a `Preprocessor` that would adapt the input shape though it sounds like the creation of an embedding layer may be more appropriate. Thanks for the pointer!

**Comment by AlexKuhnle** [comment] 2017-10-23 07:35
We don't have one currently, but that would of course also be possible (it would need to convert the input to float, too). I think an embedding layer might be a better way to handle it, though. If you build one, feel free to contribute. :-)

I will close this issue then.

**Closed by AlexKuhnle** 2017-10-23 07:35 UTC

**Comment by vwxyzjn** [comment] 2017-11-23 17:08
Hi @ImpulseAdventure ,

Did you figure out how to run envs from OpenAI Gym that incorporate a ``Discrete()`` ``observation_space``?

**Comment by AlexKuhnle** [comment] 2017-11-23 18:09
With the latest commit, there is an `Embedding` layer, see the `mlp2_embedding_network.json` example config for how it can be used.

**Comment by ImpulseAdventure** [comment] 2017-11-24 06:08
@vwxyzjn -- I did manage to adapt the envs by inserting a layer stage that converted the discrete states to a one-hot vector, but using an embedding matrix is far nicer. @AlexKuhnle thanks very much for adding this layer!

**Comment by mx781** [comment] 2018-03-24 18:55
Should this still currently work? 

Running `python examples/openai_gym.py FrozenLake-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_embedding_network.json` 

where `mlp2_embedding_network.json` is
```json
[
    {
        "type": "embedding",
        "indices": 4,
        "size": 32
    },
    {
        "type": "dense",
        "size": 32
    },
    {
        "type": "dense",
        "size": 32
    }
]
```

yields the same error as mentioned before (I am assuming `indices` should match the number of `Discrete` values). Some algorithms (TRPO for example) do not throw this error (but alas, different ones) but do not work either. Any pointers?

**Comment by michaelschaarschmidt** [comment] 2018-03-24 21:44
You have to flatten after embedding I think

**Comment by mx781** [comment] 2018-05-05 16:27
Forgot to follow up, sorry - flattening like this:
```
[
    {
        "type": "embedding",
        "indices": 16,
        "size": 4
    },
    {
        "type": "flatten"
    },
    {
        "type": "dense",
        "size": 32
    },
    {
        "type": "dense",
        "size": 32
    }
]
```

also gave the same results, with the latest tensorforce.

**Comment by AlexKuhnle** [comment] 2018-05-05 16:46
The `mlp` baseline should probably implicitly flatten before the `dense` layers, otherwise it will cause the same 'non-flattened' issue, but for the main network I would expect the `flatten` layer to be necessary nonetheless.
