### ISSUE TITLE
Problem launching example openai_gym_async 

### ISSUE THREAD

**Issue by Florence-C** [reinforceio/tensorforce#347] opened 2018-02-21 12:12 UTC
Hello

I'm trying to run the asynchronous example with openai, and I'm having troubles.

I don't get how it actually works. 
I launched the example code openai_gym_async with the line : 
`$ python examples/openai_gym_async.py CartPole-v0 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 10000 -m 200 -W 3`

which outputs : 
```
CartPole-v0 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 10000 -m 200 -W 3
kill $( lsof -i:12222-12225 -t ) > /dev/null 2>&1
tmux kill-session -t OpenAI-CartPole-v0
tmux new-session -d -s OpenAI-CartPole-v0 -n ps
tmux send-keys -t OpenAI-CartPole-v0:ps 'CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 0 --episodes 10000 --max-episode-timesteps 200 --parameter-server' Enter
tmux new-window -t OpenAI-CartPole-v0 -n worker0 -d /bin/bash
tmux send-keys -t OpenAI-CartPole-v0:worker0 'CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 0 --episodes 10000 --max-episode-timesteps 200' Enter
tmux new-window -t OpenAI-CartPole-v0 -n worker1 -d /bin/bash
tmux send-keys -t OpenAI-CartPole-v0:worker1 'CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 1 --episodes 10000 --max-episode-timesteps 200' Enter
tmux new-window -t OpenAI-CartPole-v0 -n worker2 -d /bin/bash
tmux send-keys -t OpenAI-CartPole-v0:worker2 'CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 2 --episodes 10000 --max-episode-timesteps 200' Enter
error connecting to /tmp/tmux-1000/default (No such file or directory)
```

I don't understant why I get an error with tmux, and what it means, because I can see the tmux launched the Cartpole : 
```
$ tmux ls
OpenAI-CartPole-v0: 4 windows (created Wed Feb 21 10:42:55 2018) [100x31]
```

and when I launch `$ tmux a -t OpenAI `to check what the workers are doing, I get : 

```
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARNING:tensorflow:From /home/florence/tensorflow/lib/python3.5/site-packages/tensorforce/core/distributions/categorical.py:59: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2018-02-21 10:42:58.499944: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-02-21 10:42:58.568979: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> localhost:12222}
2018-02-21 10:42:58.569020: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 127.0.0.1:12223, 1 -> 127.0.0.1:12224, 2 -> 127.0.0.1:12225}
2018-02-21 10:42:58.570718: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: `grpc://localhost:12222`
```

I tried to go on localhost i only get a weird page : 
![screenshot_localhost](https://user-images.githubusercontent.com/26022983/36479297-714e02a8-1708-11e8-8cd6-8e66ff9d8947.png)

I tried to re-launch with the flags` --mode child` and `--logdir mylogdir` to be able to store the logs, the logdir is creates but the log files remain empty. 

My questions are : 
- Is the code running properly (seems the logfiles are empty) ? 
- how can I visualize the progress of the workers (or ps) ? 
- Why is a simple runner used in this code, instead of a threaded runner ? 

Thank you in advance

**Comment by AlexKuhnle** [comment] 2018-02-21 13:19
From what I remember, I also get this tmux error and the script runs anyway. I started just ignoring it, but good point to find out why this message is thrown. Could you check the output of the other tmux windows? I assume what you posted is window 0, which runs the parameter server, hence no activity. The threaded runner does not run different processes, but only different threads within one Python process.

**Comment by Florence-C** [comment] 2018-02-21 14:11
Thanks @AlexKuhnle for your fast reply !

For the other window, the output is pretty identical : 
```
CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 0 --episodes 10000 --max-episode-timesteps 200florence@florence-pc:~/Documents/test_tensorforce$ CUDA_VISIBLE_DEVICES= /home/florence/tensorflow/bin/python /home/florence/Documents/test_tensorforce/examples/openai_gym_async.py CartPole-v0 --agent-config /home/florence/Documents/test_tensorforce/examples/configs/vpg.json --network-spec /home/florence/Documents/test_tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 0 --episodes 10000 --max-episode-timesteps 200
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARNING:tensorflow:From /home/florence/tensorflow/lib/python3.5/site-packages/tensorforce/core/distributions/categorical.py:59: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2018-02-21 14:42:21.121239: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-02-21 14:42:21.122564: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 127.0.0.1:12222}
2018-02-21 14:42:21.122585: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> localhost:12223, 1 -> 127.0.0.1:12224, 2 -> 127.0.0.1:12225}
2018-02-21 14:42:21.123241: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:12223
2018-02-21 14:42:21.218188: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 310715cd3e408303 with config:
```
(and same for the other workers)

What should appear ? And why do the logfile remain empty ? 

Thanks !

**Comment by AlexKuhnle** [comment] 2018-02-21 14:36
It should, after a few seconds, start showing rewards of the last 100 episodes etc, similar to what the non-async script is showing. What do you mean by logfiles? The TensorFlow summaries might not work properly right now, there is a problem here we still have to solve. Are you on the latest GitHub version? I ran the same line 1-2 days ago and it seemed to work fine.

**Comment by Florence-C** [comment] 2018-02-22 08:30
I was not, I used the `$ pip install tensorforce` line to install it. 
But it just reinstalled from latest Github version, and I still don't have outputs (and I don't have any either with the non-async script... I could check it works while recording videos).
And yes I was talking about tf summaries with logfiles.

**Comment by AlexKuhnle** [comment] 2018-02-22 11:17
If you don't even get outputs with the non-async script, the issue seems to be more fundamental... Please do check whether anything happens, video maybe, or just inserting a print statement [here](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym.py#L117) to see whether it ever finishes an episode. Otherwise there might be something wrong with your TensorFlow?

**Comment by michaelschaarschmidt** [comment] 2018-02-24 12:57
Hi,

could you provide us with some more info on your system? OS, Tensorflow version,..? We cannot reproduce your specific problem and at least for Alex it's running correctly.

**Comment by Florence-C** [comment] 2018-02-26 15:58
Hi, 

Sorry for the late respond. 
I use Ubuntu 16.06, a gpu GTX 960 and Tensorflow is 1.5
I reinstall everything properly, and now I have the output for the non-async version (I already could have video outputs before), but still nothing for the async version. 
I've added prints [there](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym.py#L117), where @AlexKuhnle  suggested and I can see the episode finish and the reward increases (tests are made on Cartpole). 
So it works fine, the only problem is that I cannot get logfiles for tensorboard, nor the same output that the non-async version.

**Comment by michaelschaarschmidt** [comment] 2018-02-27 19:23
Really sorry, we cannot seem to reproduce this specific issue (runs fine for one of us, while I am seeing another session problem). We are running 1.5 and 16.04, although the cpu version.  We will be looking at distributed execution modes soon though in more detail so hopefully we will uncover some of these problems.

**Comment by AlexKuhnle** [comment] 2018-07-31 17:00
I assume this problem is either solved by now or we have no good idea of how to reproduce and solve it, hence closing this for now. If there is an update, let me know.

**Closed by AlexKuhnle** 2018-07-31 17:00 UTC
