### ISSUE TITLE
How to handle a warm start

### ISSUE THREAD

**Issue by avostryakov** [reinforceio/tensorforce#83] opened 2017-08-04 10:46 UTC
Hi!

  Usually, when we train a dialogue agent with N dialogues we process with simple rule based system to get examples of successful dialogues. Without it, training process will be slow or impossible. 
  I don't see in your base example how to put N first examples in an agent without reward prediction and training.
  Can you suggest some way to do it?

**Comment by michaelschaarschmidt** [comment] 2017-08-05 08:07
You can import data into the memory agent using import_observations

**Comment by avostryakov** [comment] 2017-08-07 11:48
Thank you! 

I would like to ask another question. We used a pure Python DQN implementation from here:
https://github.com/MiuLab/TC-Bot/blob/master/src/deep_dialog/agents/agent_dqn.py#L211

In this implementation one example for training is a tuple: 
(state_t_rep, action_t, reward_t, state_tplus1_rep, episode_over)

In tensorforce we can pass only (state, action, reward) in import_observations without state after an agent action. Is it possible to do the same in tensorforce: to pass (state_before_action, action, reward, state_after_action)?

**Comment by michaelschaarschmidt** [comment] 2017-08-07 11:59
No, this is not possible. The next state is automatically the state that is observed next. Next state semantics are managed internally. You just have to import them in the order you want

**Comment by avostryakov** [comment] 2017-08-07 12:29
I see. We trying to implement the same functionality with tensorforce like in the link above. No lucky yet :) We will try to split one example into two examples. May be this help.

**Comment by AlexKuhnle** [comment] 2017-08-07 12:42
We might decide to change/extend this aspect in TensorForce at some point. But is it not possible for you to just feed the experiences in order? Also, do you consider this issue closed / feature not (yet) supported?

**Comment by avostryakov** [comment] 2017-08-07 13:29
Yes, it is possible to feed experiences in order. But we don't know why an agent doesn't learn. May be there is another reason why it doesn't learn. In this situation, it's great to be as close to code that works as possible. Other words feature not (yet) supported for us.

**Comment by AlexKuhnle** [comment] 2017-08-07 15:05
Ah, I see. If you find that the other implementation works, but ours doesn't, with same hyperparameters, that's worrying of course.

**Comment by avostryakov** [comment] 2017-08-08 09:35
We could train a DQN agent! It works.

Now we can play with PG / TRPO / PPO agents too. But... These agents don't have import_observations method. Can you add it?

**Comment by michaelschaarschmidt** [comment] 2017-08-08 09:37
That does not work from a theoretical perspective. The updates all only are guaranteed to work with on policy data, - maybe read a tutorial on policy gradient methods to understand why. 

I will close this issue then as it works as intended

**Closed by michaelschaarschmidt** 2017-08-08 09:37 UTC

**Comment by avostryakov** [comment] 2017-08-08 09:38
Thank you!
