### ISSUE TITLE
Tensorforce custom layer problem

### ISSUE THREAD

**Issue by jmelenk** [reinforceio/tensorforce#361] opened 2018-03-08 04:43 UTC
1) I created a "class Xtra(Layer):" for a custom layer to be used in a custom network and baseline.
2) There is a 4 dimesional tensor input of data to the network.
3) In the "def tf_apply(self, x, update):" function, if I use CNN for the layer variables, there are no errors in "tf_apply."   I can have multiple lines of "x = self.conv_.apply(x, update=update)" where '_' is a CNN "layer" identification number set in the __init__.  
4) I want to change the "Xtra(Layer)" class to use 2 LSTM "Layers" with a "Dense" Layer also.  
5) I first used tf.reshape() to get the input data into Matrix format (i.e. N_Rows x M_Columns).  Both are integers.
6) On using x=self.lstm_.apply(x,update=update) I get an error "TypeError: tf_apply() missing 1 required positional argument: 'state'."  I get the same error with Dense also.  

Note: seperately x=self.flatten_.apply(x,update=update) works and the x=self.lstm_.apply(x,update=update) was tested and still get the error "TypeError: tf_apply() missing 1 required positional argument: 'state'." 
7) What I'm doing wrong with steps 4), 5) and 6) to get "TypeError: tf_apply() missing 1 required positional argument: 'state'?"

**Comment by jmelenk** [comment] 2018-03-08 05:48
Extra:  The input to the network needs to be the multidimensional tensor because it contains time series information of different variables which have a different action for each member of a "slice" of the tensor.  This is what is determined by the policy.  This is what leads to "x" being reshaped in the layer.

**Comment by jmelenk** [comment] 2018-03-08 06:09
Extra: The input to the network needs to be the multidimensional tensor because it contains time series information of different variables which will have  different actions for each member of a "slice" of the tensor. This is what is determined by the policy. This is what leads to "x" being reshaped by "apply(x,update=update) of the layer. Once that is working, "x" will be reshaped and divided into parts for each set of time series data for each element that needs to have an action.

**Comment by jmelenk** [comment] 2018-03-10 20:16
I saw that the internal_lstm is for numerical data while lstm is for text.
I didn't want to upgrade until I was assured that it would for me.  Now I
will upgrade.  The actual data format and network needed will be taking a 3
dimensional tensor, then within the custom network/layer code extracting a
set of 2 dimensional tensors (matrices).  Each of the matrices will have
time series multi-variable data in them used to learn (later predict) the
fraction of each "type" of the data ("weights") for the result/reward at
each time step.

I hope upgrading to 0.3.3 does involve have to make many changes to the
code.  Would you say upgrading to the latest version available (I believe
it is 0.3.5.1 on pypi.python.com) would be better to do? I'm a bit hesitant
because I don't see documentation for 0.3.5.  If you feel 0.3.5.1 is best
for me and there is documentation, could you please provide the URL for the
documentation?

Thank you

**Comment by jmelenk** [comment] 2018-03-10 20:22
Sorry. I should have mentioned that the intermediate results from the
separate "small LSTM" to be use to get the weights, will be combined with a
convolution neural network (1x1) before the softmax is used to "convert"
the results to the actual weights.

**Comment by michaelschaarschmidt** [comment] 2018-03-10 20:45
Hi,
I think it would be recommended to use the current master, which will be converted to a new release soon. The problem is that in 0.3.5.1 there is still a number of bugs which are fixed in the current master. Documentation is always behind sadly as it's a massive effort to get everything documented, contributions welcome..

**Comment by jmelenk** [comment] 2018-03-10 21:40
Thanks for your quick response.  Just to be safe is this the link to the
current master https://github.com/reinforceio/tensorforce?

**Comment by michaelschaarschmidt** [comment] 2018-03-11 08:05
yes

**Comment by jmelenk** [comment] 2018-03-11 17:20
OK. Thank you.  JIm

**Comment by jmelenk** [comment] 2018-03-11 19:18
I also downloaded 0.3.4 because as you know https://github.com/
reinforceio/tensorforce is 0.3.5.1 and you had said there are still bugs.
I will likely go with 0.3.4 then.

**Comment by michaelschaarschmidt** [comment] 2018-03-27 14:53
Asked and answered, closing

**Closed by michaelschaarschmidt** 2018-03-27 14:53 UTC
